### ISSUE TITLE
db.php & teamkeys.db

### ISSUE THREAD

**Issue by aerosox** [OllieTerrance/IITCTeamKeys#4]
where can i get this 2 file?

**Comment by Terrance** [comment]
`db.php` is just a helper that returns a [Medoo instance](http://medoo.in/api/new).  A new database can be created using the SQL in the readme.

**Comment by aerosox** [comment]
i follow the guides but im still getting "Failed to fetch a list of teams. Retrying in 3 seconds..." in IITC

db.php

> <?
> // Or if you just download the medoo.php into directory, require it with the correct path.
> require  'medoo.php';
> 
> $database = new medoo([
>   'database_type' => 'sqlite',
>   'database_file' => 'teamkeys.db'
> ]);
> 
> $database->insert("account", [
>   "user_name" => "foo",
>   "email" => "foo@bar.com"
> ]);
> ?>

**Comment by Terrance** [comment]
db.php needs to `return $database`, and also probably shouldn't be trying to insert things...

**Comment by aerosox** [comment]
hmmm i assume is to query that right? im getting the error below

> array(1) {
>   [0]=>
>   array(8) {
>     ["id"]=>
>     string(1) "2"
>     [0]=>
>     string(1) "2"
>     ["user"]=>
>     string(11) "user"
>     [1]=>
>     string(11) "user"
>     ["team"]=>
>     string(7) "team"
>     [2]=>
>     string(7) "team"
>     ["role"]=>
>     string(1) "1"
>     [3]=>
>     string(1) "1"
>   }
> }
> <br />
> <b>Warning</b>:  Cannot modify header information - headers already sent by (output started at /*/db.php:16) in <b>/*/teamkeys.php</b> on line <b>5</b><br />
> <br />
> <b>Fatal error</b>:  Call to a member function select() on integer in <b>/*/teamkeys.php</b> on line <b>112</b><br />

**Comment by aerosox** [comment]
ok i made some changes to db.php by adding queries to it and remove the insert
```
$data = $database->query("SELECT user FROM teams")->fetchAll();
print_r($data);
```
it shows me that line 112 in teamkeys.php select() is not recognized
and i edited it to below
`                $result = $database->select("teams", "*", array("user" => $user));`


now it stuck at "Loading available Team"

with output of

```
Array
(
    [0] => Array
        (
            [user] => user01
            [0] => user01
        )

)
{"auth": true, "count": 1, "teams": [{"team": "team01", "role": 1}]}
```

**Comment by aerosox** [comment]
return $database as in query?

**Comment by Terrance** [comment]
Not sure what you mean by query.  The entire contents of my db.php looks like this:

``` php
<?
require_once getenv("PHPLIB") . "medoo.min.php";
return new medoo([
    "database_type" => "sqlite",
    "database_file" => getenv("DATA") . $dbFile
]);
```

Here, `$dbFile` is defined by the script that imports db.php.  You probably don't want the `getenv()` calls as part of your require paths (though PHP may default that to empty for you).

The alternative is not to have a db.php at all (I only use this as I have many projects using SQLite DBs in a standard place) -- just replace lines 3 and 4 in teamkeys.php with:

``` php
require_once "medoo.php";
$db = new medoo(["database_type" => "sqlite", "database_file" => "teamkeys.db"]);
```
